const SOURCES = {
  api: { label: "API Brand", copy: "Operational and aggregated marketplace signals from the API ingest source.", metrics: [["product_count", "Products"], ["observation_count", "Observations"], ["seller_count", "Sellers"], ["avg_price", "Average price"], ["avg_rating", "Average rating"]], historyMetrics: [["product_count", "Product Count"], ["observation_count", "Observation Count"], ["seller_count", "Seller Count"], ["avg_price", "Average Price"], ["median_price", "Median Price"], ["avg_rating", "Average Rating"], ["total_rating_count", "Total Rating Count"], ["rating_coverage_pct", "Rating Coverage"], ["avg_stock_qty", "Average Stock Quantity"]], interpretationMetrics: [["median_price", "Median price"], ["product_count", "Product count"], ["avg_rating", "Average rating"]], profile: [["Products", "product_count"], ["Observations", "observation_count"], ["Sellers", "seller_count"], ["Average price", "avg_price"], ["Median price", "median_price"], ["Average rating", "avg_rating"], ["Rating coverage", "rating_coverage_pct"], ["Average stock", "avg_stock_qty"], ["Top seller", "top_seller"], ["Price tier", "price_tier"]], columns: [["Brand", "brand"], ["Products", "product_count"], ["Observations", "observation_count"], ["Sellers", "seller_count"], ["Average price", "avg_price"], ["Median price", "median_price"], ["Average rating", "avg_rating"], ["Rating coverage", "rating_coverage_pct"], ["Average stock", "avg_stock_qty"], ["Price tier", "price_tier"]], catalogSorts: [["brand", "Brand"], ["median_price", "Median Price"], ["avg_rating", "Average Rating"], ["rating_coverage_pct", "Rating Coverage"], ["product_count", "Product Count"], ["observation_count", "Observation Count"], ["seller_count", "Seller Count"], ["avg_price", "Average Price"], ["avg_stock_qty", "Average Stock Quantity"]] },
  scraper: { label: "Scraper Brand", copy: "Consumer-facing marketplace presence and observed catalog characteristics from the web scraper source.", metrics: [["listing_volume", "Listing volume"], ["product_variety_count", "Product variety"], ["category_count", "Categories"], ["median_price", "Median price"], ["avg_rating", "Average rating"]], historyMetrics: [["listing_volume", "Listing Volume"], ["product_variety_count", "Product Variety"], ["category_count", "Category Count"], ["median_price", "Median Price"], ["avg_rating", "Average Rating"], ["rating_coverage_pct", "Rating Coverage"]], interpretationMetrics: [["median_price", "Median price"], ["listing_volume", "Listing volume"], ["avg_rating", "Average rating"]], profile: [["Listing volume", "listing_volume"], ["Product variety", "product_variety_count"], ["Categories", "category_count"], ["Top category", "top_category"], ["Median price", "median_price"], ["Average rating", "avg_rating"], ["Rating coverage", "rating_coverage_pct"], ["Price tier", "price_tier"]], columns: [["Brand", "brand"], ["Listing Volume", "listing_volume"], ["Product Variety", "product_variety_count"], ["Categories", "category_count"], ["Median Price", "median_price"], ["Average Rating", "avg_rating"], ["Rating Coverage", "rating_coverage_pct"], ["Price Tier", "price_tier"]], catalogSorts: [["brand", "Brand"], ["median_price", "Median Price"], ["avg_rating", "Average Rating"], ["rating_coverage_pct", "Rating Coverage"], ["listing_volume", "Listing Volume"], ["product_variety_count", "Product Variety Count"], ["category_count", "Category Count"]] }
};

function escapeHtml(value) { return String(value ?? "").replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[character])); }
function numeric(value) { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : null; }
function display(value) { if (value === null || value === undefined || value === "") return "Unavailable"; const parsed = numeric(value); return parsed === null ? escapeHtml(value) : parsed.toLocaleString(undefined, { maximumFractionDigits: 2 }); }
function features(sourceState) { return Array.isArray(sourceState.data?.features) ? sourceState.data.features : []; }
function timeseries(sourceState, brand) { return (Array.isArray(sourceState.data?.timeseries) ? sourceState.data.timeseries : []).filter((record) => String(record.brand) === String(brand) && !Number.isNaN(new Date(record.day).getTime())).slice().sort((a, b) => new Date(a.day) - new Date(b.day)); }

function ranking(source, rows) {
  const items = source.metrics.flatMap(([field, label]) => rows.filter((row) => numeric(row[field]) !== null).map((row) => ({ row, label, value: numeric(row[field]) }))).sort((a, b) => b.value - a.value).slice(0, 6);
  if (!items.length) return `<div class="visual-empty" role="status"><strong>No ranking data is available.</strong><span>Rankings appear only when the source returns numeric measurements.</span></div>`;
  const maximum = Math.max(...items.map((item) => item.value), 1);
  return `<div class="ranking-list">${items.map((item, index) => `<div class="ranking-item"><div class="ranking-label"><span class="ranking-number">${index + 1}</span><span class="ranking-name">${escapeHtml(item.row.brand)}</span><strong>${item.label}: ${display(item.value)}</strong></div><div class="ranking-track"><span class="ranking-fill" style="width:${Math.max(3, item.value / maximum * 100)}%"></span></div></div>`).join("")}</div>`;
}

function searchResults(sourceState) {
  const query = sourceState.searchQuery.trim().toLowerCase();
  const rows = features(sourceState).filter((row) => String(row.brand ?? "").toLowerCase().includes(query)).slice(0, 8);
  if (!rows.length) return `<p class="empty-copy">${query ? "No matching brands were found in the loaded source." : "No brand records are available in this source."}</p>`;
  return `<div class="search-results">${rows.map((row) => `<button class="search-result" type="button" data-brand-select="${escapeHtml(row.brand)}"><strong>${escapeHtml(row.brand || "Unnamed brand")}</strong><span>${row.brand === sourceState.selectedBrand ? "Selected" : "Select brand"}</span></button>`).join("")}</div>`;
}

function profile(source, sourceState) {
  const row = features(sourceState).find((item) => String(item.brand) === String(sourceState.selectedBrand));
  if (!row) return `<div class="empty-panel" role="status"><strong>No brand selected.</strong><span>Search the loaded source and select a brand to inspect its profile.</span></div>`;
  return `<div class="profile-grid">${source.profile.map(([label, field]) => `<div class="profile-item"><span>${label}</span><strong>${display(row[field])}</strong></div>`).join("")}</div>`;
}

function catalogRows(source, sourceState) {
  const catalogState = sourceState.catalog;
  const query = catalogState.query.trim().toLowerCase();
  const filtered = features(sourceState).filter((row) => {
    const brandMatches = !query || String(row.brand ?? "").toLowerCase().includes(query);
    const tierMatches = !catalogState.priceTier || String(row.price_tier ?? "") === catalogState.priceTier;
    return brandMatches && tierMatches;
  });
  const rows = filtered.slice();
  const direction = catalogState.sortDirection === "desc" ? -1 : 1;
  rows.sort((left, right) => {
    const leftValue = left[catalogState.sortKey]; const rightValue = right[catalogState.sortKey];
    const leftMissing = leftValue === null || leftValue === undefined || leftValue === "";
    const rightMissing = rightValue === null || rightValue === undefined || rightValue === "";
    if (leftMissing || rightMissing) return leftMissing === rightMissing ? 0 : leftMissing ? 1 : -1;
    const leftNumber = numeric(leftValue); const rightNumber = numeric(rightValue);
    if (catalogState.sortKey === "brand") return String(leftValue).localeCompare(String(rightValue), undefined, { sensitivity: "base" }) * direction;
    if (leftNumber !== null && rightNumber !== null) return (leftNumber - rightNumber) * direction;
    return String(leftValue).localeCompare(String(rightValue), undefined, { sensitivity: "base" }) * direction;
  });
  return { rows, totalPages: Math.max(1, Math.ceil(rows.length / 25)) };
}

function catalog(source, sourceState) {
  const catalogState = sourceState.catalog;
  const { rows, totalPages } = catalogRows(source, sourceState);
  const page = Math.min(Math.max(1, catalogState.page), totalPages);
  const start = rows.length ? (page - 1) * 25 : 0;
  const pageRows = rows.slice(start, start + 25);
  const tiers = [...new Set(features(sourceState).map((row) => row.price_tier).filter((tier) => tier !== null && tier !== undefined && tier !== ""))].sort((left, right) => String(left).localeCompare(String(right), undefined, { sensitivity: "base" }));
  const table = pageRows.length ? `<div class="catalog-table-wrap"><table class="catalog-table"><thead><tr>${source.columns.map(([label]) => `<th scope="col">${label}</th>`).join("")}</tr></thead><tbody>${pageRows.map((row) => `<tr>${source.columns.map(([, field], index) => `<td>${index === 0 ? `<button class="catalog-product-button" type="button" data-brand-select="${escapeHtml(row.brand)}" data-brand-focus="true">${display(row[field])}</button>` : display(row[field])}</td>`).join("")}</tr>`).join("")}</tbody></table></div><div class="catalog-pagination"><span>Showing ${start + 1}–${start + pageRows.length} of ${rows.length}</span><span>Page ${page} of ${totalPages}</span><div><button class="button-secondary" type="button" data-brand-catalog-page="prev" ${page <= 1 ? "disabled" : ""}>Previous</button><button class="button-secondary" type="button" data-brand-catalog-page="next" ${page >= totalPages ? "disabled" : ""}>Next</button></div></div>` : `<div class="catalog-empty"><strong>${features(sourceState).length ? "No brands match the current catalog search or filter." : "No catalog records are available."}</strong><span>${features(sourceState).length ? "Try a different brand search or Price Tier." : "The active source returned an empty features list."}</span></div>`;
  return `<div class="catalog-toolbar"><label class="field-label">Search brands<input id="brand-catalog-search" type="search" placeholder="Search by brand" value="${escapeHtml(catalogState.query)}" /></label><label class="field-label">Price Tier<select id="brand-catalog-price-tier" ${tiers.length ? "" : "disabled"}><option value="">All tiers</option>${tiers.map((tier) => `<option value="${escapeHtml(tier)}" ${String(catalogState.priceTier) === String(tier) ? "selected" : ""}>${escapeHtml(tier)}</option>`).join("")}</select></label><label class="field-label">Sort by<select id="brand-catalog-sort">${source.catalogSorts.map(([field, label]) => `<option value="${field}" ${catalogState.sortKey === field ? "selected" : ""}>${label}</option>`).join("")}</select></label><label class="field-label">Direction<select id="brand-catalog-direction"><option value="asc" ${catalogState.sortDirection === "asc" ? "selected" : ""}>Ascending</option><option value="desc" ${catalogState.sortDirection === "desc" ? "selected" : ""}>Descending</option></select></label></div>${table}`;
}

function historicalChart(source, sourceState) {
  if (!sourceState.selectedBrand) return `<div class="visual-empty" role="status"><strong>No brand selected.</strong><span>Select a brand before viewing historical trends.</span></div>`;
  const metric = sourceState.historicalMetric;
  const label = source.historyMetrics.find(([field]) => field === metric)?.[1] || source.historyMetrics[0][1];
  const matched = timeseries(sourceState, sourceState.selectedBrand);
  if (!matched.length) return `<div class="visual-empty" role="status"><strong>No matching historical records.</strong><span>No timeseries records match the selected brand in the active source.</span></div>`;
  const usable = matched.map((record) => ({ record, value: numeric(record[metric]), date: new Date(record.day) })).filter(({ record, value, date }) => value !== null && !Number.isNaN(date.getTime()) && !(metric === "avg_rating" && recordRatingCoverage(record) === 0));
  if (!usable.length) return `<div class="visual-empty" role="status"><strong>No usable ${escapeHtml(label.toLowerCase())} values.</strong><span>The active source does not contain valid numeric observations for this metric.</span></div>`;
  if (usable.length < 2) return `<div class="visual-empty" role="status"><strong>Insufficient evidence for ${escapeHtml(label.toLowerCase())} history.</strong><span>At least two usable chronological observations are required.</span></div>`;
  const width = 760; const height = 280; const left = 58; const right = 18; const top = 24; const bottom = 50;
  const values = usable.map((item) => item.value); const minimum = Math.min(...values); const maximum = Math.max(...values); const range = maximum - minimum || 1; const xStep = (width - left - right) / (usable.length - 1);
  const points = usable.map((item, index) => `${left + index * xStep},${top + (maximum - item.value) / range * (height - top - bottom)}`).join(" ");
  const circles = usable.map((item, index) => { const x = left + index * xStep; const y = top + (maximum - item.value) / range * (height - top - bottom); return `<circle class="trend-point" cx="${x}" cy="${y}" r="4"><title>${escapeHtml(formatDate(item.record.day))}: ${escapeHtml(display(item.value))}</title></circle>`; }).join("");
  const first = usable[0].record.day; const last = usable[usable.length - 1].record.day;
  return `<div class="trend-chart-wrap"><svg class="trend-chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="${escapeHtml(label)} history for ${escapeHtml(sourceState.selectedBrand)}"><line class="chart-axis" x1="${left}" y1="${top}" x2="${left}" y2="${height - bottom}"/><line class="chart-axis" x1="${left}" y1="${height - bottom}" x2="${width - right}" y2="${height - bottom}"/><polyline class="trend-line" fill="none" points="${points}"/>${circles}<text class="chart-label" x="${left}" y="${height - 18}">${escapeHtml(formatDate(first))}</text><text class="chart-label" text-anchor="end" x="${width - right}" y="${height - 18}">${escapeHtml(formatDate(last))}</text><text class="chart-label" x="${left}" y="14">${escapeHtml(label)}</text></svg><p class="chart-note">${usable.length} usable observations shown; null and non-numeric values are excluded without interpolation.</p></div>`;
}

function recordRatingCoverage(record) { return numeric(record.rating_coverage_pct); }
function formatDate(value) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "Unavailable" : date.toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" }); }

function interpretationValues(sourceState, field) {
  return timeseries(sourceState, sourceState.selectedBrand).map((record) => ({ record, value: numeric(record[field]), date: new Date(record.day) })).filter(({ record, value, date }) => value !== null && !Number.isNaN(date.getTime()) && !(field === "avg_rating" && recordRatingCoverage(record) === 0));
}

function interpretationValue(field, value) {
  const countFields = ["product_count", "observation_count", "seller_count", "total_rating_count", "listing_volume", "product_variety_count", "category_count"];
  const fractionDigits = countFields.includes(field) ? 0 : 2;
  const formatted = Number(value).toLocaleString(undefined, { maximumFractionDigits: fractionDigits });
  return field === "rating_coverage_pct" ? `${formatted}%` : formatted;
}

function deterministicObservation(sourceState, field, label) {
  const values = interpretationValues(sourceState, field);
  if (!values.length) return null;
  if (values.length < 2) return `The latest recorded ${label.toLowerCase()} was ${interpretationValue(field, values[0].value)} on ${formatDate(values[0].record.day)}.`;
  const first = values[0];
  const latest = values[values.length - 1];
  const direction = latest.value > first.value ? "increased" : latest.value < first.value ? "decreased" : "remained unchanged";
  if (direction === "remained unchanged") return `${label} remained unchanged at ${interpretationValue(field, first.value)} from ${formatDate(first.record.day)} to ${formatDate(latest.record.day)}.`;
  return `${label} ${direction} from ${interpretationValue(field, first.value)} on ${formatDate(first.record.day)} to ${interpretationValue(field, latest.value)} on ${formatDate(latest.record.day)}.`;
}

function renderDeterministicInterpretation(source, sourceState) {
  if (!sourceState.selectedBrand) return `<div class="empty-panel compact" role="status"><strong>No brand selected.</strong><span>Select a brand to derive direct observations from its historical measurements.</span></div>`;
  const matching = timeseries(sourceState, sourceState.selectedBrand);
  if (!matching.length) return `<div class="empty-panel compact" role="status"><strong>No matching historical records.</strong><span>No timeseries records match the selected brand in the active source.</span></div>`;
  const observations = source.interpretationMetrics.map(([field, label]) => deterministicObservation(sourceState, field, label)).filter(Boolean).slice(0, 5);
  if (!observations.length) return `<div class="empty-panel compact" role="status"><strong>No usable measurements for interpretation.</strong><span>The matching historical records do not contain sufficient valid numeric evidence.</span></div>`;
  return `<div class="interpretation-list">${observations.map((observation) => `<article class="interpretation-item"><p>${escapeHtml(observation)}</p></article>`).join("")}</div><p class="data-note">Direct observations from ${escapeHtml(source.label)} measurements. No causal or recommended conclusions are applied.</p>`;
}

function insightText(value) { if (value === null || value === undefined) return null; return typeof value === "string" ? value : JSON.stringify(value); }
function appendInsightField(parent, label, value) { const text = insightText(value); if (text === null || text === "") return; const field = document.createElement("div"); field.className = "insight-field"; const fieldLabel = document.createElement("span"); fieldLabel.className = "card-kicker"; fieldLabel.textContent = label; const fieldValue = document.createElement("p"); fieldValue.className = "insight-text"; fieldValue.textContent = text; field.append(fieldLabel, fieldValue); parent.append(field); }
function appendInsightSection(parent, title, renderContent) { const section = document.createElement("section"); section.className = "insight-block"; const heading = document.createElement("h4"); heading.textContent = title; section.append(heading); renderContent(section); parent.append(section); }
function appendInsightEmpty(parent, message) { const empty = document.createElement("p"); empty.className = "insight-empty"; empty.setAttribute("role", "status"); empty.textContent = message; parent.append(empty); }
function appendInsightItems(parent, items, fieldLabels) { if (!Array.isArray(items) || items.length === 0) { appendInsightEmpty(parent, "No backend items are available for this section."); return; } items.forEach((item) => { const card = document.createElement("article"); card.className = "insight-item"; fieldLabels.forEach(([field, label]) => appendInsightField(card, label, item?.[field])); parent.append(card); }); }
function appendInsightSpotlights(parent, spotlights, source) { const order = ["top_brand", "fastest_rising", "under_pressure"]; const labels = { top_brand: "Top brand", fastest_rising: "Fastest rising", under_pressure: "Under pressure" }; const fields = source === "api" ? [["brand", "Brand"], ["metric", "Metric"], ["significance", "Significance"]] : [["name", "Brand"], ["metric", "Metric"], ["strategic_value", "Strategic value"]]; let rendered = 0; order.forEach((key) => { const spotlight = spotlights && typeof spotlights === "object" ? spotlights[key] : null; if (!spotlight || typeof spotlight !== "object") return; const card = document.createElement("article"); card.className = "insight-item"; const title = document.createElement("h5"); title.textContent = labels[key]; card.append(title); fields.forEach(([field, label]) => appendInsightField(card, label, spotlight[field])); parent.append(card); rendered += 1; }); if (!rendered) appendInsightEmpty(parent, "No backend entity spotlights are available."); }

export function renderBrandInsight(root, state) {
  const container = root.querySelector("[data-brand-insight]"); if (!container) return; container.replaceChildren(); const activeSource = state.brand.activeSource; const sourceState = state.brand[activeSource];
  if (sourceState.status !== "success") { appendInsightEmpty(container, sourceState.status === "loading" ? "AI insight will appear after the source payload loads." : sourceState.status === "error" ? "AI insight is unavailable because the source request failed." : "AI insight is unavailable until the source payload loads."); return; }
  const insight = sourceState.data?.insight; if (!insight || typeof insight !== "object") { appendInsightEmpty(container, "AI insight unavailable for this source."); return; }
  appendInsightField(container, "Role", insight.role);
  appendInsightSection(container, "Executive summary", (section) => { if (insight.executive_summary === null || insight.executive_summary === undefined || insight.executive_summary === "") appendInsightEmpty(section, "Executive summary unavailable."); else appendInsightField(section, "Executive summary", insight.executive_summary); });
  appendInsightSection(container, "Key findings", (section) => appendInsightItems(section, insight.key_findings, [["finding", "Finding"], ["evidence", "Evidence"], ["confidence", "Confidence"], ["confidence_reason", "Confidence basis"]]));
  const opportunityFields = activeSource === "api" ? [["opportunity", "Opportunity"], ["implication", "Implication"]] : [["opportunity", "Opportunity"], ["description", "Description"], ["actionability", "Actionability"]]; appendInsightSection(container, "Opportunities", (section) => appendInsightItems(section, insight.opportunities, opportunityFields));
  const riskFields = activeSource === "api" ? [["risk", "Risk"], ["implication", "Implication"]] : [["risk", "Risk"], ["description", "Description"], ["mitigation_strategy", "Mitigation strategy"]]; appendInsightSection(container, "Risks", (section) => appendInsightItems(section, insight.risks, riskFields));
  appendInsightSection(container, "Entity spotlights", (section) => appendInsightSpotlights(section, insight.entity_spotlights, activeSource));
}

export function renderBrand(state) {
  const active = state.brand.activeSource;
  const sourceState = state.brand[active];
  const source = SOURCES[active];
  const loaded = sourceState.status === "success";
  const status = { idle: "Not loaded", loading: "Loading data", success: "Data loaded", error: "Load failed" }[sourceState.status];
  return `<section class="content brand-content" aria-labelledby="brand-page-title"><div class="content-header product-header"><div><div class="module-kicker">Intelligence module</div><h2 id="brand-page-title">Brand Intelligence</h2><p class="content-intro">Explore brand signals while preserving the distinct analytical meaning of API and scraper sources.</p></div><span class="module-state state-${sourceState.status}"><span class="state-dot" aria-hidden="true"></span>${status}</span></div>
    <section class="brand-source-panel" aria-labelledby="brand-source-title"><div><span class="card-kicker">Source context</span><h3 id="brand-source-title">Choose the analytical source</h3><p>${source.copy}</p></div><div class="source-toggle" role="group" aria-label="Brand data source"><button class="source-button ${active === "api" ? "is-active" : ""}" type="button" data-brand-source="api" aria-pressed="${active === "api"}">API Brand</button><button class="source-button ${active === "scraper" ? "is-active" : ""}" type="button" data-brand-source="scraper" aria-pressed="${active === "scraper"}">Scraper Brand</button></div></section>
    ${sourceState.status === "loading" ? `<div class="product-notice loading-notice" role="status"><span class="state-dot" aria-hidden="true"></span>Requesting ${source.label} data from the configured FastAPI service…</div>` : ""}${sourceState.status === "error" ? `<div class="product-notice error-notice" role="alert"><strong>Unable to load ${source.label}.</strong><span>${escapeHtml(sourceState.error || "The Brand request failed.")}</span><button class="button-secondary" type="button" data-brand-action="retry">Retry</button></div>` : ""}
    <section class="product-section orientation-section" aria-labelledby="brand-orientation-title"><div class="section-heading"><div><span class="card-kicker">Dataset orientation</span><h3 id="brand-orientation-title">Understand the loaded source</h3></div><p>Counts reflect the response returned by the selected Brand endpoint.</p></div><div class="orientation-grid"><div class="orientation-item"><span>Feature records</span><strong>${loaded ? display(features(sourceState).length) : "Loading"}</strong></div><div class="orientation-item"><span>Timeseries records</span><strong>${loaded ? display(sourceState.data.timeseries.length) : "Loading"}</strong></div><div class="orientation-item"><span>Source</span><strong>${loaded ? escapeHtml(sourceState.data.features?.[0]?.source || sourceState.data.timeseries?.[0]?.source || source.label) : "Loading"}</strong></div><div class="orientation-item"><span>Insight payload</span><strong>${loaded && sourceState.data.insight ? "Returned" : loaded ? "Unavailable" : "Loading"}</strong></div></div></section>
    <section class="product-section" aria-labelledby="brand-market-title"><div class="section-heading"><div><span class="card-kicker">Understand</span><h3 id="brand-market-title">Market overview</h3></div><p>Bounded rankings use only measurements from the active source.</p></div><div class="visual-card">${loaded ? ranking(source, features(sourceState)) : `<div class="visual-empty" role="status"><strong>${sourceState.status === "error" ? "Overview unavailable." : "Brand data is not loaded."}</strong><span>Real source measurements will appear after the request succeeds.</span></div>`}</div></section>
    <section class="product-section discovery-section" aria-labelledby="brand-discovery-title"><div class="section-heading"><div><span class="card-kicker">Discover</span><h3 id="brand-discovery-title">Brand discovery</h3></div><p>Search loaded feature records by their exact source-level brand value.</p></div><div class="discovery-panel"><label class="field-label" for="brand-search">Search brands</label><div class="search-row"><input id="brand-search" type="search" placeholder="Search ${source.label} brands" value="${escapeHtml(sourceState.searchQuery)}" ${loaded ? "" : "disabled"} /><span class="search-count">${loaded ? "Results limited to 8" : "Unavailable"}</span></div><div data-brand-results>${loaded ? searchResults(sourceState) : `<p class="empty-copy">${sourceState.status === "loading" ? "Brand records are being requested." : "Brand intelligence data is not loaded."}</p>`}</div></div></section>
    <section class="product-section profile-section" aria-labelledby="brand-profile-title"><div class="section-heading"><div><span class="card-kicker">Investigate</span><h3 id="brand-profile-title">Selected Brand Profile</h3></div><p>Profile metrics remain specific to the active source schema.</p></div>${loaded ? profile(source, sourceState) : `<div class="empty-panel" role="status"><strong>No brand selected.</strong><span>The source profile is unavailable until real Brand data is loaded.</span></div>`}</section>
    <section class="product-section" aria-labelledby="brand-history-title"><div class="section-heading"><div><span class="card-kicker">Historical evidence</span><h3 id="brand-history-title">Historical trends</h3></div><p>Matching records are filtered by exact brand identity and sorted chronologically.</p></div><div class="visual-card"><div class="visual-toolbar"><label for="brand-history-metric">Measure<select id="brand-history-metric" data-brand-control="historical-metric" ${loaded && sourceState.selectedBrand ? "" : "disabled"}>${source.historyMetrics.map(([field, label]) => `<option value="${field}" ${sourceState.historicalMetric === field ? "selected" : ""}>${label}</option>`).join("")}</select></label></div>${loaded ? historicalChart(source, sourceState) : `<div class="visual-empty" role="status"><strong>${sourceState.status === "error" ? "Historical data unavailable." : "Brand data is not loaded."}</strong><span>Historical charts reuse the active Brand payload after it loads.</span></div>`}</div></section>
    <div class="product-detail-grid"><section class="product-section" aria-labelledby="brand-deterministic-title"><div class="section-heading"><div><span class="card-kicker">Traceable evidence</span><h3 id="brand-deterministic-title">Deterministic Interpretation</h3></div><p>Direct observations from the active source measurements.</p></div>${loaded ? renderDeterministicInterpretation(source, sourceState) : `<div class="empty-panel compact" role="status"><strong>Interpretation unavailable.</strong><span>Measured data must be loaded before deterministic observations can be derived.</span></div>`}</section><section class="product-section ai-section" aria-labelledby="brand-ai-title"><div class="section-heading"><div><span class="card-kicker ai-kicker">Backend-generated interpretation</span><h3 id="brand-ai-title">AI Executive Insight</h3></div><div class="ai-insight-body" data-brand-insight></div></section></div>
    <section class="product-section" aria-labelledby="brand-catalog-title"><div class="section-heading"><div><span class="card-kicker">Investigate</span><h3 id="brand-catalog-title">Brand catalog</h3></div><p>Source-specific columns only; full pagination is deferred.</p></div>${loaded ? catalog(source, sourceState) : `<div class="catalog-empty"><strong>Catalog unavailable.</strong><span>Load the active source to inspect returned feature records.</span></div>`}</section></section>`;
}

export function bindBrandControls(root, actions) { root.querySelectorAll("[data-brand-source]").forEach((button) => button.addEventListener("click", () => actions.onSource(button.dataset.brandSource))); root.querySelector("#brand-search")?.addEventListener("input", (event) => actions.onSearch(event.target.value)); root.querySelector("[data-brand-action=retry]")?.addEventListener("click", actions.onRetry); root.querySelector("[data-brand-control=historical-metric]")?.addEventListener("change", (event) => actions.onHistoricalMetric(event.target.value)); root.querySelector("#brand-catalog-search")?.addEventListener("input", (event) => actions.onCatalogSearch(event.target.value)); root.querySelector("#brand-catalog-price-tier")?.addEventListener("change", (event) => actions.onCatalogFilter(event.target.value)); root.querySelector("#brand-catalog-sort")?.addEventListener("change", (event) => actions.onCatalogSort(event.target.value)); root.querySelector("#brand-catalog-direction")?.addEventListener("change", (event) => actions.onCatalogDirection(event.target.value)); root.querySelectorAll("[data-brand-catalog-page]").forEach((button) => button.addEventListener("click", () => actions.onCatalogPage(button.dataset.brandCatalogPage))); root.querySelectorAll("[data-brand-select]").forEach((button) => button.addEventListener("click", () => actions.onSelect(button.dataset.brandSelect, button.dataset.brandFocus === "true"))); }
